Convert enum to string option
sonata-project/EntityAuditBundle pull request #400
Opened 2021-06-15 13:58 UTC by michealmouner

## Subject

I am targeting this branch, because I need to add a new features to the bundle
I added a boolean option to convert EnumToString incase you are using it in the DB (it causes problems)
```
convert_enum_to_string: true # default to false
```

example of created ENUM migration
```
$this->addSql('ALTER TABLE table_name ADD enum_column ENUM(\'option_1\', \'option_2\', \'option_3\') DEFAULT \'option_3\' NOT NULL');
$this->addSql('ALTER TABLE table_name ADD enum_column VARCHAR(255) DEFAULT \'option_3\'');
```

## Changelog

```markdown
### Added
two new options:
- convert_enum_to_string --> if true, it will convert Enum value to string in audit table

### Fixed
src/SimpleThings/EntityAudit/Utils/SimpleDiff.php:26 --> fix undefined variable

```

2021-07-13 09:32 UTC, VincentLanglet submitted a review, later dismissed

2021-07-13 09:33 UTC, VincentLanglet commented
Can you take a look @phansys ?

2021-07-17 20:57 UTC, phansys requested changes
Could we add a test for this feature?

2021-07-17 20:57 UTC, phansys commented on src/Utils/SimpleDiff.php
> +        $nmax = 0;
These variables seem to be unused in this method.

2021-07-18 14:51 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-07-26 11:41 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-10-28 08:42 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2022-05-03 10:10 UTC, closed without merging