Feature/many to many support
sonata-project/EntityAuditBundle pull request #509
Opened 2022-08-18 12:14 UTC by pietaj

I am targeting this branch, because the bundle does not support m:n auditing and the subject was already mentioned 
here https://github.com/sonata-project/EntityAuditBundle/issues/302, and here https://github.com/sonata-project/EntityAuditBundle/pull/321 but was never finished

2022-08-18 12:33 UTC, VincentLanglet commented
I fixed the cs in https://github.com/sonata-project/EntityAuditBundle/pull/510.

Please rebase and revert the extra style changes

2022-08-22 13:41 UTC, pietaj commented
I've rebased the code and reverted the style changes.

I've also left the deprecation fixes out of this PR as it makes the code harder to review.

2022-08-24 19:47 UTC, pietaj commented
@VincentLanglet I've checked the stan / psalm issues reported by the CI and I can fix them, no problem, but this will make the code changes in this PR even more complex, as there are quite a lot of things to review already. Shall I proceed with the fixes and throw them all in a separate commit?  What would be the most convenient way to proceed?

2022-08-24 19:56 UTC, VincentLanglet requested changes

2022-08-24 19:56 UTC, VincentLanglet commented on src/AuditReader.php
> +                        ).$assoc['joinTable']['name'].$this->config->getTableSuffix();
```suggestion
                    $tableName = $this->config->getTablePrefix()
                        .$assoc['joinTable']['name']
                        .$this->config->getTableSuffix();
```

2022-08-24 19:56 UTC, VincentLanglet commented on src/AuditReader.php
> +                        ).' DESC';
Prefer using sprintf

2022-08-24 19:56 UTC, VincentLanglet commented on src/AuditReader.php
> +                            ).$targetAssoc['joinTable']['name'].$this->config->getTableSuffix();
```suggestion
                        $tableName = $this->config->getTablePrefix()
                            .$targetAssoc['joinTable']['name']
                            .$this->config->getTableSuffix();
```

2022-08-24 19:56 UTC, VincentLanglet commented on src/AuditReader.php
> +                            ).' DESC';
prefer sprintf

2022-08-24 19:56 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +     * @psalm-param array{cache?: array, cascade: array<string>, declared?: class-string, fetch: mixed, fieldName: string, id?: bool, inherited?: class-string, indexBy?: string, inversedBy: null|stri
You can use @phpstan-import-type AssociationMapping from ... https://github.com/doctrine/orm/blob/2.13.x/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L110
instead on the class level.

And then use it in the phpdoc.

2022-08-24 19:56 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +     * @param ClassMetadata $class
```suggestion
     * @param ClassMetadata<object> $class
```
avoid the need of psalm-param

2022-08-24 19:56 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +     * @psalm-param ClassMetadata<object> $targetClass
We prefer phpstan-param

2022-08-24 19:56 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +            if (!(($assoc['type'] & ClassMetadata::TO_ONE) === 0
Change !($a || $b ||$c) to !a && !b && !c

2022-08-24 19:57 UTC, VincentLanglet commented
> @VincentLanglet I've checked the stan / psalm issues reported by the CI and I can fix them, no problem, but this will make the code changes in this PR even more complex, as there are quite a lot of things to review already. Shall I proceed with the fixes and throw them all in a separate commit? What would be the most convenient way to proceed?

Yes please fix the issues. 

Lot of them where already fix on some others places of the code with some if checks or some assert. You can do the same.

2022-08-24 20:02 UTC, pietaj commented
> > @VincentLanglet I've checked the stan / psalm issues reported by the CI and I can fix them, no problem, but this will make the code changes in this PR even more complex, as there are quite a lot of things to review already. Shall I proceed with the fixes and throw them all in a separate commit? What would be the most convenient way to proceed?
> 
> Yes please fix the issues.
> 
> Lot of them where already fix on some others places of the code with some if checks or some assert. You can do the same.

Oh my, thanks for the ultra fast reply, I didn't mean to push ;) I will fix all issues and will come back to you after everything will pass green

2022-09-04 08:21 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2022-09-15 05:12 UTC, VincentLanglet commented
Any issue @pietaj ? :)

2022-09-23 13:36 UTC, pietaj commented
My only issue was my day job :) did the requested psalm / phpstan compliance cleanup and the requested changes

2022-09-23 13:45 UTC, VincentLanglet commented
> My only issue was my day job :) did the requested psalm / phpstan compliance cleanup and the requested changes

Seems like build is still failing

2022-09-23 14:03 UTC, pietaj commented
That's odd ... both rector and phpstan pass on dev machine. I'll have a closer look

2022-09-23 14:05 UTC, VincentLanglet commented
> That's odd ... both rector and phpstan pass on dev machine. I'll have a closer look

Tru to update your dependencies maybe ?

2022-09-23 14:10 UTC, pietaj commented
yeah, thanks for the tip. Outdated dependencies, I'll rerun and fix the rest

2022-09-26 09:06 UTC, pietaj commented
@VincentLanglet one of the failing checks is linked with rector, failing with

`PHP Fatal error:  Uncaught _PHPStan_9a6ded56a\Nette\DI\InvalidConfigurationException: The item 'conditionalTags › PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule › phpstan.rules.rule' expects to be bool, array given. in phar:///home/runner/work/EntityAuditBundle/EntityAuditBundle/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:219`

I did some quick checks and the error is linked with phpstan/phpstan bumping from `1.8.5 => 1.8.6`. Did you encounter a similar problems in other sonata projects as well?

2022-09-26 09:20 UTC, jordisala1991 commented
> @VincentLanglet one of the failing checks is linked with rector, failing with
> 
> `PHP Fatal error: Uncaught _PHPStan_9a6ded56a\Nette\DI\InvalidConfigurationException: The item 'conditionalTags › PHPStan\Rules\DisallowedConstructs\DisallowedLooseComparisonRule › phpstan.rules.rule' expects to be bool, array given. in phar:///home/runner/work/EntityAuditBundle/EntityAuditBundle/vendor/rector/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Compiler.php:219`
> 
> I did some quick checks and the error is linked with phpstan/phpstan bumping from `1.8.5 => 1.8.6`. Did you encounter a similar problems in other sonata projects as well?

Yes, ignore rector for now.

2022-09-27 21:32 UTC, VincentLanglet requested changes
It's ok for me, except some formatting issues.
Is this PR ok for you @jordisala1991 ?

2022-09-27 21:32 UTC, VincentLanglet commented on src/AuditReader.php
> +            ) && !$classMetadata->isIdentifier($field)
This reformatting is weird. I would prefer
```suggestion
            $tableAlias = $classMetadata->isInheritanceTypeJoined()
                && $classMetadata->isInheritedField($field)
                && !$classMetadata->isIdentifier($field)
```

2022-09-27 21:32 UTC, VincentLanglet commented on src/AuditReader.php
> +                ) && !$classMetadata->isIdentifier($field)
```suggestion
                $tableAlias = $classMetadata->isInheritanceTypeJoined()
                    && $classMetadata->isInheritedField($field)
                    && !$classMetadata->isIdentifier($field)
```

2022-09-27 21:32 UTC, VincentLanglet commented on src/AuditReader.php
> +            ).' WHERE '.$whereSQL.' ORDER BY r.id DESC';
this formatting is weird

2022-09-27 21:32 UTC, VincentLanglet commented on src/AuditReader.php
> +                            )->associationMappings[$mappedBy];
this formatting is weird

2022-09-27 21:32 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +     * @psalm-param ClassMetadata<object> $targetClass
```suggestion
     * @phpstan-param ClassMetadata<object> $targetClass
```

2022-09-27 21:32 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +            // $tableName = $this->config->getTableName($class);
Why adding a code commented ? can we remove it ?

2022-09-27 21:46 UTC, jordisala1991 reviewed
Do we need more information on the readme, or should we only remove the last todo?

2022-09-27 21:46 UTC, jordisala1991 commented on tests/RelationTest.php
> +     * This test verifies the temporary behaviour of audited entities with M-M relationships.
I think this comment is outdated. The behavior implemented right now is not temporary right?

2022-09-27 21:46 UTC, jordisala1991 commented
This Pr also needs a changelog.

2022-09-28 10:03 UTC, VincentLanglet approved these changes, later dismissed

2022-09-28 10:08 UTC, VincentLanglet approved these changes

2022-10-08 19:11 UTC, jordisala1991 approved these changes

2022-10-08 19:11 UTC, merged

2022-10-08 19:11 UTC, jordisala1991 commented
Thanks @pietaj

2022-10-08 19:12 UTC, jordisala1991 commented
I guess the todo list on the readme should be updated too.