Add support for PSR clock
sonata-project/EntityAuditBundle pull request #536
Opened 2023-02-08 17:03 UTC by X-Coder264

## Subject

I am targeting this branch, because it adds a new feature without a BC-break.

## Changelog

```markdown
### Added
- Support for PSR ClockInterface

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

2023-02-08 18:04 UTC, VincentLanglet requested changes

2023-02-08 18:04 UTC, VincentLanglet commented on src/EventListener/LogRevisionsListener.php
> +                    Types::DATETIME_IMMUTABLE,
Isn't this change a BC-break ? I dunno what it imply.

2023-02-08 18:04 UTC, VincentLanglet commented on tests/BaseTest.php
> +    protected function getClock(): ClockInterface
This should return null by default instead to test that we correctly work without clock.
```suggestion
    protected function getClock(): ?ClockInterface
    {
         return null;
    }
```

2023-02-08 23:14 UTC, X-Coder264 commented on tests/BaseTest.php
> +    protected function getClock(): ClockInterface
Done

2023-02-08 23:21 UTC, X-Coder264 commented on src/EventListener/LogRevisionsListener.php
> +                    Types::DATETIME_IMMUTABLE,
It's not a BC break. The query either executes or it doesn't (it obviously executes fine as all the tests are passing).

All the types do is tell DBAL which `\Doctrine\DBAL\Types\Type` child class to use to get the value to bind to the query, more specifically in this case whether to call `\Doctrine\DBAL\Types\DateTimeType::convertToDatabaseValue` or `\Doctrine\DBAL\Types\DateImmutableType::convertToDatabaseValue`.

2023-02-08 23:23 UTC, VincentLanglet approved these changes

2023-02-13 10:45 UTC, merged

2023-02-13 10:45 UTC, VincentLanglet commented
Thanks