use event_listener instead of event_subscriber
sonata-project/EntityAuditBundle pull request #583
Opened 2023-08-01 12:25 UTC by Hanmac

## Subject

I am targeting this branch, because it should be BC.

## Changelog

```markdown
### Fixed
- Deprecation of Event Subscribers on Symfony 6.3. They now uses Event Listeners
```

2023-08-01 18:58 UTC, VincentLanglet approved these changes

2023-08-01 19:00 UTC, VincentLanglet requested changes
Lot of tests are failing here...

2023-08-01 19:00 UTC, VincentLanglet commented on src/EventListener/CreateSchemaListener.php
> +     * NEXT_MAJOR: remove this method.
```suggestion
     * NEXT_MAJOR: remove this method.
     *
     * @return string[]
```
instead ; same for others

2023-08-01 23:07 UTC, VincentLanglet commented
I think less tests are failing

2023-08-02 08:39 UTC, VincentLanglet commented on src/DependencyInjection/SimpleThingsEntityAuditExtension.php
> +            $tags = $definition->getTag('doctrine.event_listener');
The method `fixParametersFromDoctrineEventSubscriberTag` can be renamed
`fixParametersFromDoctrineEventListenerTag`

2023-08-02 09:05 UTC, Hanmac commented
hm i don't know what causes this `some_strange_key_name` one to fail ?

2023-08-02 10:43 UTC, franmomu commented
> hm i don't know what causes this `some_strange_key_name` one to fail ?

I guess is the last release of `doctrine/orm` (2.16), I've created https://github.com/sonata-project/EntityAuditBundle/pull/584

2023-08-02 12:38 UTC, VincentLanglet commented
> > hm i don't know what causes this `some_strange_key_name` one to fail ?
> 
> I guess is the last release of `doctrine/orm` (2.16), I've created #584

It's merged, please rebase

2023-08-03 09:02 UTC, VincentLanglet approved these changes

2023-08-03 09:03 UTC, merged